apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: dpass-upload
    workspace: .
    docker: {}
    bazel: null
  local:
    skipPush: null
  googleCloudBuild: null
  kaniko: null
deploy:
  helm: null
  kubectl:
    manifests:
    - skaffold-deployment.yaml
